subsampling: {}

reading:
    yt_args:
        download_size: 1080
        download_audio: False
        yt_metadata_args:
            writesubtitles:  True
            subtitleslangs: ['en']
            writeautomaticsub: True
            get_info: True
    timeout: 60
    sampler: null

storage:
    number_sample_per_shard: 100
    oom_shard_count: 5
    captions_are_subtitles: False

distribution:
    processes_count: 3
    thread_count: 3
    subjob_size: 10000
    distributor: "multiprocessing"
